### ISSUE TITLE
Default experiments are not converging

### ISSUE THREAD

**Issue by ipsec** [DHDev0/Stochastic-muzero#3]
Hi Daniel,

I'm running the experiment_450_config.json without modifications with this command:

```
python muzero_cli.py train report config/experiment_450_config.json
```

And I'm getting this report:

![model_450_data_of_the_average_reward](https://user-images.githubusercontent.com/79345/228044547-c26e8db6-70b5-4127-aba0-9d49281a7841.png)

Is mandatory to run `python muzero_cli.py human_buffer config/experiment_450_config.json` before train?

**Comment by DHDev0** [comment]
Can you try again with the docker ? I test it a month ago for a similar issue.

**Comment by ipsec** [comment]
I'm unable to build the docker image.
I'm getting this error while running `docker build -t stochastic_muzero .`:

```
#8 25.99 Collecting box2d-py==2.3.5
#8 26.01   Downloading box2d-py-2.3.5.tar.gz (374 kB)
#8 26.02      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.4/374.4 kB 62.0 MB/s eta 0:00:00
#8 26.06   Preparing metadata (setup.py): started
#8 26.25   Preparing metadata (setup.py): finished with status 'done'
#8 26.62 ERROR: Ignored the following versions that require a different python version: 0.7 Requires-Python >=3.6, <3.7; 0.8 Requires-Python >=3.6, <3.7
#8 26.62 ERROR: Could not find a version that satisfies the requirement ale-py~=0.8.0 (from versions: none)
#8 26.62 ERROR: No matching distribution found for ale-py~=0.8.0
------
executor failed running [/bin/sh -c apt-get -y update     && apt-get install --no-install-recommends -y     unzip     libglu1-mesa-dev     libgl1-mesa-dev     libosmesa6-dev     xvfb     patchelf     ffmpeg cmake     && apt-get autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/*     && mkdir /root/.mujoco     && cd /root/.mujoco     && wget -qO- 'https://github.com/deepmind/mujoco/releases/download/2.1.0/mujoco210-linux-x86_64.tar.gz' | tar -xzvf -    && pip install --upgrade pip     && cd     && cd /app     && pip install -r requirements.txt]: exit code: 1
```

**Comment by DHDev0** [comment]
Could you upload your dockerfile here ? just to confirm the python version

**Comment by ipsec** [comment]
I'm building now with `docker build --platform linux/amd64 -t stochastic_muzero .`

Let me test under docker to verify the results.

**Comment by ipsec** [comment]
Don't run over M1 chip.

**Comment by DHDev0** [comment]
Can't test the M1 but since you use cpu i don't see why it wouldn't work. What is your virtual environment ? (I test on ubuntu 19 and 20 )

**Comment by DHDev0** [comment]
You closed the ticket so I conclude you were able to fix it. ( pytorch cpu should work on M1 )
Let me know if you need help with docker.
