### ISSUE TITLE
Questions about is_chance label assignment

### ISSUE THREAD

**Issue by timothijoe** [DHDev0/Stochastic-muzero#4]
When I run monte_carlo_tree_search.py, I found the decision node and chance node do not alternate within a search path.

Normally, we would expect a search path to look like this: [decision node, chance node, decision node, chance node, ...].
However, after running the code, the result is: [decision node, decision node, chance node, chance node, ...]. 

I believe the issue arises within the create_new_node_in_the_chosen_node_with_action_and_policy function. We should assign the value of is_child_chance to self.node.is_chance instead of self.node.children[i].is_chance.

**Comment by DHDev0** [comment]
If you don't specify a correct player cycle and a number of simulation superior to 2, it's not gonna alternate between decision tree and chance node. For example the 450 example use only the prior for fast compute. Else you will find other json hyperparameter using the mcts simulation superior to 2. Refer to mcts doc for more details.

Also i don't know how you recover the tree(would help to understand which hyperparameter you use and what you did) but the most important number is the count of branch of the prior from the root. (nomal example you gave would be for 1 action)

**Comment by timothijoe** [comment]
Thank you for your kind response. I am using the parameters from config/experiment_450_config.json, and I have set num_simulations = 10.

Another reason I have the above question is that, in the paper "Planning Stochastic Environments with A Learned Model", within the pseudocode on page 24 of the appendix, inside the expand_node() function, it assigns a value to node.is_chance instead of node.children[i].is_chance.

I am not sure if the function self.create_new_node_in_the_chosen_node_with_action_and_policy() serves the same purpose as expand_node() in the pseudocode, or if it has other functionalities, which is why the assignment of is_chance has been placed in node.children[i].is_chance instead.

Looking forward to your patient explanation.

**Comment by DHDev0** [comment]
- I generalize the cycle to specify the type of node inside the node when it gets created. But in the pseucode they assign the type of node when they are using the node as a sub-root to generate node. It's equivalent.

- They use this function to get the player cycle "class ActionOutcomeHistory:" page 22 which they use as argument for run_mcts. since the cycle is ouside the mcts they have to give the argument from top to bottom of the mcts, i just do it internally since i already know the cycle. Which is probably not the best approach if the game isn't cyclic, for example player 1 keep player untill it win before player 2 can play.

**Comment by timothijoe** [comment]
Thank you for your kind response.  
I still have some misunderstanding about the children of self.root. 
Normally, the children of self.root should be "is_chance = True", so that in the search path,
decision node and chance node alternate within a search path. (Here I assume the self.root is the decision node, and the child of self.root is chance node)

However, in the function self.expand_the_children_of_the_root_node(), 
self.root.children[i].is_chance is set to False.

Is there any misunderstanding on my part regarding certain aspects of this issue?

**Comment by DHDev0** [comment]
You have two expand node function:
 - [expand_the_children_of_the_root_node] Which will expand from the root multiple decision node to initiate the graph.
 - [create_new_node_in_the_chosen_node_with_action_and_policy] Which will expand node with this shift between decision node and chance node.

**Comment by timothijoe** [comment]
Yes, in my opinion, in [expand_the_children_of_the_root_node] , self.root.children[i].is_chance should set to "True". (Currently it is set to False). If so, there is no problem in [create_new_node_in_the_chosen_node_with_action_and_policy].

However,  in Line211 of monte_carlo_tree_search.py, self.root.children[i] = False, I wonder if it is the reason the decision node and chance node do not alternate within a search path, when I run the code with the parameters from config/experiment_450_config.json, and num_simulations = 10. 
![debug_mcts](https://user-images.githubusercontent.com/49814804/228163219-5b4d0308-5333-4ece-9f58-03d54217d054.png)

**Comment by DHDev0** [comment]
| (number of action = 2) | Decision_node = DN | Chance_node = CD | Action_1 = A1 | root node is alone and  just holding an initial state and count path |

![graph](https://user-images.githubusercontent.com/104598708/228171533-f8cde069-4d40-45c9-b2d5-99a4304e7541.PNG)

If you set it to true under you root node you will have chance node instead of decision node.(page:6 https://openreview.net/pdf?id=X6D9bAHhBQ1)
The ordering you see in search path isn't the order of the graph but an accumulated graph ordering. so your link show the path from root to the left cd_a1 and cd_a2

**Comment by timothijoe** [comment]
Thank you for your patient explanation. 
My confusion mainly arises from why the root node's children cannot be chance nodes. 

In your example above, the root node's children (DN_A1 and DN_A2) are set as decision nodes.
An in  the original paper's diagram (as illustrated by the picture below), s_0 is the root node, which is a decision node. However, the node as_0, as a child of s_0, is a chance node. 

Is it that my understanding of the article is somewhat skewed, or has the code implementation made some adjustments in this regard?

![stochastic_tree_search](https://user-images.githubusercontent.com/49814804/228215357-1d28ece1-3c8c-4aa6-8fe9-6d126e026930.jpg)

**Comment by DHDev0** [comment]
This should clarify the misunderstanding:

The graph you are looking at embed the graph I show. Meaning when I show you [cd_a1,cd_a2] or [dn_a1,dn_a2] each of this list represent one block ( decision node or chance node )

The root hold the state of the game. S_0 is the initial hidden state of the game ( not the state ) generated by the representation model using the actual state(root) of the game, S_1 will be the state generated by the dynamics model using S_0. Then S_2 will be the state generated by the dynamics model using S_1 generated by the dynamics model.

**Comment by DHDev0** [comment]
Look like you don't have more question.
Let me know If you need help to understand anything else.
