### ISSUE TITLE
What about merging with SpeedyZero code base?

### ISSUE THREAD

**Issue by GrigoryEvko** [DHDev0/Stochastic-muzero#6]
Hi! Thanks for implementing that Deepmind paper. What do you think about merging with some highly optimized distributed implementation of the MuZero family member ([SpeedyZero](https://openreview.net/forum?id=Mg5CLXZgvLJ)). It's essentially an EfficientZero, but on juice (from the same authors). With c++ cpu and partially gpu MCTS module, efficient buffer and many more. I think, it's more relevant to muzero-unplugged implementation,  but isn't the stochastic version not much different?
I think I am going to implement some changes from SpeedyZero into your implementation on my own, but if you are interested, you can create a new branch and we will work on it there together.
Code for the SpeedyZero in the [Supplementary materials](https://openreview.net/attachment?id=Mg5CLXZgvLJ&name=supplementary_material).

Thanks for the code again!

**Comment by GrigoryEvko** [comment]
P.S. https://github.com/DHDev0/Stochastic-time-series-forecast-simulator
Ah, I see what you're up to. Me too. IMHO, external predictor is required, RL on its own wouldn't be enough. Can share something in DM or email.

**Comment by DHDev0** [comment]
I would be glad to do it. I was waiting for pytorch 2.1 to accelerate the the training and inference with compile and quantization.
Perhaps it's better to create a new repo for it. Discord channel so you will be able to dm: https://discord.gg/KR4NyrPX
Also invite you to an other repo.

**Comment by DHDev0** [comment]
Will continue on an other repo. Discord is open if anyone else want to participate.

**Comment by DHDev0** [comment]
Cancelled
