### ISSUE TITLE
the results of stochastic-muzero?

### ISSUE THREAD

**Issue by Jackory** [DHDev0/Stochastic-muzero#8]
Hi, thanks for your implementation. Is there any results of this implementation compared to Muzero Unplugged  in offline setting, or Muzero in online setting?

**Comment by Jackory** [comment]
I see that the results for Cartpole is not stable, and even can not converge to the average episode rewards of `500`. I wonder your comment on the report. Thanks!

**Comment by DHDev0** [comment]
I'm sure with some effort you will find it :+1: !

**Comment by DHDev0** [comment]
You are open to ask anything, it just need to make sense,,,
